apiVersion: v1
kind: Service
metadata:
  name: farmerzon-authentication-cip
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  type: ClusterIP 
  selector:
    app: farmerzon-authentication-sts