apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmerzon-authentication-deploy
  labels:
    app: microservice-authentication
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: microservice-authentication
  template:
    metadata:
      labels:
        app: microservice-authentication
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "farmerzon-authentication"
        dapr.io/app-port: "5000"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: farmerzon-authentication
        image: patrikhuber/farmerzon-authentication:latest
        imagePullPolicy: "Always"
        env:
        - name: ConnectionStrings__FarmerzonAuthentication
          value: "UserId=postgres;Password='1[Pa$$$$word]1';Server=35.205.255.64;Port=5432;Database=farmerzon-authentication-db;IntegratedSecurity=True;Pooling=True;Enlist=True"
        - name: AllowedOrigins__0
          value: "http://raspiancluster.farmerzon.net"
        ports:
        - containerPort: 5000
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 5000
        #   initialDelaySeconds: 10
        # readinessProbe:
        #   periodSeconds: 15
        #   timeoutSeconds: 2
        #   successThreshold: 2
        #   failureThreshold: 2
        #   httpGet:
        #     path: /healthz
        #     port: 5000
