apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: farmerzon-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /authentication
        backend:
          serviceName: farmerzon-authentication-ingress-cip
          servicePort: 5000
      - path: /backend
        backend:
          serviceName: farmerzon-backend-ingress-cip
          servicePort: 5000