apiVersion: v1
kind: Service
metadata:
  name: farmerzon-frontend-ingress-cip
  labels:
    app: microservice-frontend
spec:
  ports:
  - port: 5000
    name: microservice-frontend
  type: NodePort 
  selector:
    app: microservice-frontend