apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: farmerzon-ingress
spec:
  rules:
  - host: api.authentication.farmerzon.local
    http:
      paths:
      - path: /
        backend:
          serviceName: farmerzon-authentication-ingress-cip
          servicePort: 5000
  - host: api.backend.farmerzon.local
    http:
      paths:
      - path: /
        backend:
          serviceName: farmerzon-backend-ingress-cip
          servicePort: 5000
#  - host: farmerzon.local
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: farmerzon-frontend-ingress-cip
#          servicePort: 5000