apiVersion: v1
kind: Service
metadata:
  name: farmerzon-articles-cip
  labels:
    app: postgres-articles
spec:
  ports:
  - port: 5432
    name: postgres-articles
  type: NodePort 
  selector:
    app: postgres-articles