microk8s helm3 install postgres bitnami/postgresql 
    --set image.repository=arm64v8/postgres 
    --set image.tag=11.6
    --set persistence.storageClass=microk8s-hostpapth
    --set persistence.size=10Gi 
    --set postgresqlDataDir=/data/pgdata 
    --set persistence.mountPath=/data
    --set volumePermissions.image.repository=arm32v7/alpine 
    --set volumePermissions.image.tag=3.10 
    --set securityContext.fsGroup=999 
    --set securityContext.runAsUser=999 
    --set livenessProbe.initialDelaySeconds=300 
    --set readinessProbe.initialDelaySeconds=300 