version: "3"

services:
  farmerzon-authentication:
    container_name: farmerzon-authentication
    build: ./farmerzon-authentication/.
    ports: 
      - 5000:5000
    depends_on:
      - farmerzon-authentication-db
    networks:
      - farmerzon-network
    environment:
      - ConnectionStrings__FarmerzonAuthentication=UserId=admin;Password=password;Server=farmerzon-authentication-db;Port=5432;Database=farmerzon-authentication-db;IntegratedSecurity=True;Pooling=True;Enlist=True

  farmerzon-authentication-dapr:
    image: "daprio/daprd:0.11.2"
    command: ["./daprd",
      "-app-id", "farmerzon-authentication",
      "-app-port", "5000",
      "-components-path", "/components"]
    depends_on:
      - farmerzon-authentication
    network_mode: "service:farmerzon-authentication"

  farmerzon-articles:
    container_name: farmerzon-articles
    build: ./farmerzon-articles/.
    ports:
      - 5001:5000
    depends_on:
      - farmerzon-articles-db
    networks:
      - farmerzon-network
    environment:
      - ConnectionStrings__FarmerzonArticles=UserId=admin;Password=password;Server=farmerzon-articles-db;Port=5432;Database=farmerzon-articles-db;IntegratedSecurity=True;Pooling=True;Enlist=True

  farmerzon-articles-dapr:
    image: "daprio/daprd:0.11.2"
    command: ["./daprd",
      "-app-id", "farmerzon-articles",
      "-app-port", "5000",
      "-components-path", "/components"]
    depends_on:
      - farmerzon-articles
    network_mode: "service:farmerzon-articles"

  farmerzon-address:
    container_name: farmerzon-address
    build: ./farmerzon-address/.
    ports:
      - 5002:5000
    depends_on:
      - farmerzon-address-db
    networks:
      - farmerzon-network
    environment:
      - ConnectionStrings__FarmerzonAddress=UserId=admin;Password=password;Server=farmerzon-address-db;Port=5432;Database=farmerzon-address-db;IntegratedSecurity=True;Pooling=True;Enlist=True

  farmerzon-address-dapr:
    image: "daprio/daprd:0.11.2"
    command: ["./daprd",
      "-app-id", "farmerzon-address",
      "-app-port", "5000",
      "-components-path", "/components"]
    depends_on:
      - farmerzon-address
    network_mode: "service:farmerzon-address"

  farmerzon-backend:
    container_name: farmerzon-backend
    build: ./farmerzon-backend/.
    ports:
      - 5003:5000
    depends_on:
      - farmerzon-address
      - farmerzon-articles
      - farmerzon-authentication
    networks:
      - farmerzon-network

  farmerzon-backend-dapr:
    image: "daprio/daprd:0.11.2"
    command: ["./daprd",
      "-app-id", "farmerzon-backend",
      "-app-port", "5000",
      "-components-path", "/components"]
    depends_on:
      - farmerzon-backend
    network_mode: "service:farmerzon-backend"

  farmerzon-frontend:
    container_name: farmerzon-frontend
    build: ./farmerzon-frontend/.
    ports:
      - 3000:3000
    depends_on:
      - farmerzon-address
      - farmerzon-articles
      - farmerzon-authentication
    networks:
      - farmerzon-network

  farmerzon-authentication-db:
    container_name: farmerzon-authentication-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=farmerzon-authentication-db
    ports:
      - 5432:5432
    networks:
      - farmerzon-network
  
  farmerzon-articles-db:
    container_name: farmerzon-articles-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=farmerzon-articles-db
    ports:
      - 5433:5432
    networks:
      - farmerzon-network

  farmerzon-address-db:
    container_name: farmerzon-address-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=farmerzon-address-db
    ports:
      - 5434:5432
    networks:
      - farmerzon-network

  farmerzon-recipies-db:
    container_name: farmerzon-recipies-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=farmerzon-recipies-db
    ports:
      - 5435:5432
    networks:
      - farmerzon-network

networks:
  farmerzon-network: