version: "3"

services:
  farmerzon-authentication:
    container_name: farmerzon-authentication
    build: ./farmerzon-authentication/.
    ports: 
      - 5000:5000

  farmerzon-articles:
    container_name: farmerzon-articles
    build: ./farmerzon-articles/.
    ports:
      - 5001:5000

  farmerzon-address:
    container_name: farmerzon-address
    build: ./farmerzon-address/.
    ports:
      - 5002:5000

  farmerzon-backend:
    container_name: farmerzon-backend
    build: ./farmerzon-backend/.
    ports:
      - 5003:5000
    environment:
      - BaseUrls__FarmerzonAddress__Host=farmerzon-address
      - BaseUrls__FarmerzonAddress__Port=5000
      - BaseUrls__FarmerzonArticles__Host=farmerzon-articles
      - BaseUrls__FarmerzonArticles__Port=5000

  farmerzon-frontend:
    container_name: farmerzon-frontend
    build: ./farmerzon-frontend/.
    ports:
      - 5004:3000