apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-04T19:12:47Z"
  labels:
    app: farmerzon-frontend
  name: farmerzon-frontend-service
  namespace: default
  resourceVersion: "142611"
  selfLink: /api/v1/namespaces/default/services/farmerzon-frontend-service
  uid: 60785f7c-a697-11ea-a07f-42010a8401d1
spec:
  clusterIP: 10.4.13.144
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31246
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: farmerzon-frontend
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.77.131.35
