apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-04T19:11:08Z"
  generation: 2
  labels:
    app: farmerzon-frontend
  name: farmerzon-frontend
  namespace: default
  resourceVersion: "143250"
  selfLink: /apis/apps/v1/namespaces/default/deployments/farmerzon-frontend
  uid: 25287092-a697-11ea-a07f-42010a8401d1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: farmerzon-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: farmerzon-frontend
    spec:
      containers:
      - image: lukbraun/farmerzon-frontend
        imagePullPolicy: Always
        name: farmerzon-frontend-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-04T19:11:28Z"
    lastUpdateTime: "2020-06-04T19:11:28Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-04T19:11:08Z"
    lastUpdateTime: "2020-06-04T19:11:28Z"
    message: ReplicaSet "farmerzon-frontend-77bb77f588" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
