apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: farmerzon-order-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: farmerzon-order-db
spec:
  selector:
    app: farmerzon-order-db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmerzon-order-db
spec:
  selector:
    matchLabels:
      app: farmerzon-order-db
  template:
    metadata:
      labels:
        app: farmerzon-order-db
    spec:
      containers:
        - name: farmerzon-order-db
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: farmerzon-order-db-pvc
